services:
  searxng:
    container_name: ${HARBOR_CONTAINER_PREFIX}.searxng
    env_file:
      - ./.env
      - ./searxng/override.env
    image: searxng/searxng
    environment:
      INSTANCE_NAME: searxng
      BASE_URL: http://0.0.0.0:8080
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./searxng:/etc/searxng
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    ports:
      - ${HARBOR_SEARXNG_HOST_PORT}:8080
    networks:
      - harbor-network
